### PR TITLE
Cleaning up Warnings 

### PR DESCRIPTION
**Pull request by vitasam**
Cleaning up Warnings

### CODE REVIEW

**Comment by abhra0897** [comment]
Thanks! I'll later modify horizontal and vertical line drawing functions to avoid using that macro.

**Comment by vitasam** [comment]
Hi, sounds good!

**Comment by vitasam** [comment]
Hello,
one more comment: could you also add some Monospaced fonts? E.g. with sizes 8, 12, 16?

**Comment by abhra0897** [comment]
Sure I'll do it. Though, I'm not sure when as my company discontinued work-from-home and now I've little time to work on my personal projects.

**Comment by vitasam** [comment]
Thanks! No problem!

**Comment by abhra0897** [comment]
> Thanks! No problem!

Hi @vitasam , I've added a few more fonts, but more importantly, I wrote a tutorial on "how to make font". Check here: https://github.com/abhra0897/FontsEmbedded.git

I'll update the info in this display driver repo soon.

**Comment by vitasam** [comment]
Hi,

Thanks! This tool is a great addition!

**Comment by vitasam** [comment]
Great job!

**Pull request merged**
